name: srilankancargo_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^3.0.0
  url_launcher: ^6.3.0
  device_info: ^2.0.0
  device_info_plus: ^9.1.1
  flutter_svg: ^2.0.10+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  webview_flutter: ^4.8.0
  webview_flutter_platform_interface: ^2.10.0
  
  #flutter_webview_plugin: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/2022451025672_Big-removebg-preview (1).png
     - assets/images/139.png
     - assets/images/239378279_1992974014190829_3029728983071132528_n.jpg
     - assets/images/EmQ9_FuVcAIrkfw.jpg
     - assets/images/unnamed.png
     - assets/images/Image-DE_SLA.png
     - assets/images/appicon.png
     - assets/images/visit_website_banner.png 
     - assets/images/homescreen_image_1.jpg
     - assets/images/homescreen_image_2.jpg
     - assets/images/homescreen_image_3.jpg
     - assets/images/about_us_icon.svg
     - assets/images/home_icon.svg
     - assets/images/contact_us_icon.svg
     - assets/images/flight_status_icon.svg
     - assets/images/flight_schedule_icon.svg
     
     - assets/images/loadability_icon.svg
     - assets/images/storage_calculator_icon.svg
     - assets/images/volume_calculator_icon.svg
     - assets/images/tracking_icon.svg
     - assets/images/homescreen_banner.jpg
     - assets/images/about_us_picture.jpg
     - assets/images/call_us_icon.svg
     - assets/images/email_us_icon.svg
     - assets/images/address_icon.svg
     - assets/images/youtube_icon.svg
     - assets/images/instagram_icon.svg
     - assets/images/facebook_icon.svg
     - assets/images/x_icon.svg
     - assets/images/linkedin_icon.svg

     - assets/images/flight_status.png
     - assets/images/flight_schedule.png
     - assets/images/terms_and_conditions.png
     - assets/images/loadability.png
     - assets/images/terms_icon.svg
     
     - assets/images/volume_calculator.png
     - assets/images/storage_calculator.png



     
     
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SriLankan Regular
      fonts:
        - asset: fonts/SriLankan Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
