name: srilankancargo_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^3.0.0
  url_launcher: ^6.3.0
  device_info: ^2.0.0
  device_info_plus: ^9.1.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  webview_flutter: ^4.8.0
  webview_flutter_platform_interface: ^2.10.0
  xml: ^6.5.0
  dropdown_search: ^5.0.6
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0




flutter:
  uses-material-design: true

  assets:
     - assets/images/2022451025672_Big-removebg-preview (1).png
     - assets/images/139.png
     - assets/images/239378279_1992974014190829_3029728983071132528_n.jpg
     - assets/images/EmQ9_FuVcAIrkfw.jpg
     - assets/images/unnamed.png
     - assets/images/Image-DE_SLA.png
     - assets/images/appicon.png
     - assets/images/visit_website_banner.png 
     - assets/images/homescreen_image_1.jpg
     - assets/images/homescreen_image_2.jpg
     - assets/images/homescreen_image_3.jpg
     - assets/images/about_us_icon.svg
     - assets/images/home_icon.svg
     - assets/images/contact_us_icon.svg
     - assets/images/flight_status_icon.svg
     - assets/images/flight_schedule_icon.svg
     - assets/images/loadability_icon.svg
     - assets/images/storage_calculator_icon.svg
     - assets/images/volume_calculator_icon.svg
     - assets/images/tracking_icon.svg
     - assets/images/homescreen_banner.jpg
     - assets/images/about_us_picture.jpg
     - assets/images/call_us_icon.svg
     - assets/images/email_us_icon.svg
     - assets/images/address_icon.svg
     - assets/images/youtube_icon.svg
     - assets/images/instagram_icon.svg
     - assets/images/facebook_icon.svg
     - assets/images/x_icon.svg
     - assets/images/linkedin_icon.svg
     - assets/images/flight_status.png
     - assets/images/flight_schedule.png
     - assets/images/terms_and_conditions.png
     - assets/images/loadability.png
     - assets/images/terms_icon.svg
     - assets/images/volume_calculator.png
     - assets/images/storage_calculator.png
     - assets/images/airplane_line.svg
     - assets/images/homescreen_banner_new.jpg
     - assets/images/home_background_banner_try.png
     - assets/images/cross.svg
     - assets/images/tick.svg
     - assets/images/android12splash.jpg
     - assets/images/logo_white.png
    
  fonts:
    - family: SriLankan Regular
      fonts:
        - asset: fonts/SriLankan Regular.ttf
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"